-- FORMQ: 문의/신고하기
CREATE TABLE NOTICE (
   	FORMQESEQ 	  NUMBER  		 PRIMARY KEY,
	FORMQCATE1    VARCHAR2(50)					 NOT NULL, 
	FORMQCATE2    VARCHAR2(50)  				 NOT NULL, 
	FORMQEMAIL1   VARCHAR2(100)					 NOT NULL
	FORMQEMAIL2   VARCHAR2(100) 				 NOT NULL
	FORMQPHONE1   VARCHAR2(15)  				 NOT NULL
	FORMQPHONE2   VARCHAR2(15) 				     NOT NULL
	FORMQPHONE3   VARCHAR2(15)  				 NOT NULL
	FORMQCONTENT  VARCHAR2(4000) 				 NOT NULL,
	FORMQRCPTDATE VARCHAR2(30)   DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE FORMQSEQ NOCACHE NOCYCLE;



-- NOTICE: 공지사항
CREATE TABLE NOTICE (
   	NOTICESEQ 	  NUMBER   PRIMARY KEY,
	NOTICESUBJECT VARCHAR2 NOT NULL, 
	NOTICECONTENT VARCHAR2 NOT NULL, 
	NOTICEDATE 	  VARCHAR2 NOT NULL
);

CREATE SEQUENCE NOTICESEQ NOCACHE NOCYCLE;

